# Generated by Django 3.2.4 on 2021-06-27 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 27, 14, 15, 58, 811427)),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
