# Generated by Django 3.2.4 on 2021-07-03 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 3, 20, 49, 56, 836995)),
        ),
    ]
