# Generated by Django 3.2.4 on 2021-07-03 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 3, 20, 51, 9, 235908)),
        ),
    ]
